version: '2'

services:
  spark:
    image: # your image
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '4040:4040'
      - '4041:4041'
    volumes:
      - ./:/streaming
  spark-worker:
    image: eecs4415/spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '28081:8081'
      - '24040:4040'
      - '24041:4041'
    volumes:
      - ./:/streaming
  data-source:
    image: # your image
    volumes:
      - ./:/streaming
    environment:
      - TOKEN=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
    command: python3.9 -u /streaming/data_source.py
#  webapp:
#    image: # your image
#    volumes:
#      - ./:/streaming
#    ports:
#      - '5000:5000'
#    command:
  redis:
    image: redis
