version: '2' # Using Docker Compose file format version 2

services:
  spark:
    image: # Replace with your Docker image for Spark master
    environment:
      - SPARK_MODE=master
      # ... other env variables ...
    ports:
      - '8080:8080'
      # ... other ports ...
    volumes:
      - ./:/streaming

  spark-worker:
    image: project/spark # Note: This is a custom image. Replace with an image that has the required Spark dependencies.
    environment:
      - SPARK_MODE=worker
      # ... other env variables ...
    ports:
      - '28081:8081'
      # ... other ports ...
    volumes:
      - ./:/streaming

  data-source:
    image: # Replace with your Docker image for the data source
    volumes:
      - ./:/streaming
    environment:
      - TOKEN=${TOKEN} # Set your GitHub token in your environment variables
    command: python3.9 -u /streaming/data_source.py

# Placeholder for potential future web application
#  webapp:
#    image: # Replace with your Docker image for web app
#    volumes:
#      - ./:/streaming
#    ports:
#      - '5000:5000'
#    command: ...

  redis:
    image: redis # Using official Redis image
